import { Weekend } from "./types";

export const initialWeekends: Weekend[] = [
  {
    id: 1,
    title: "The Rite of First Forging",
    goal: "Construct the Sacred Tracker",
    deliverable: "A functioning cogitator interface to chronicle the 10 Sacred Rites",
    doneWhen: "The tracker awakens, Rite I is inscribed, and faith in the machine is established",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 2,
    title: "The Cartography of Machine Spirits",
    goal: "Map the Personal AI Topography",
    deliverable: "Model Topography Scroll and 'Canticles of Tool Selection' document",
    doneWhen: "You divine which machine spirit serves which purpose without hesitation",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 3,
    title: "The Deep Communion Sprint",
    goal: "Channel a week's research through sacred afternoon communion",
    deliverable: "A 2-page research brief bearing clear recommendation",
    doneWhen: "The brief yields wisdom you would trust to guide your actions",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 4,
    title: "The Rite of Data Purification",
    goal: "Transform corrupted data into sacred decisions",
    deliverable: "Purified dataset and one-page Insights Manifest with actionable directives",
    doneWhen: "You name the 3 prime drivers and your ordained response",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 5,
    title: "The Visual Cognition Protocol",
    goal: "Grant the machine sight and reason",
    deliverable: "One sanctified infographic, diagram, or visual codex",
    doneWhen: "The visual transmits understanding faster than mere words",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 6,
    title: "The Information Conduit",
    goal: "Forge your NotebookLM + Gamma neural pathway",
    deliverable: "Reusable workflow: Summary + FAQ + Presentation from single input",
    doneWhen: "You can brief an adept on material in under 7 minutes using your deck",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 7,
    title: "The First Automation Rite",
    goal: "Birth your content distribution servitor",
    deliverable: "One functioning automation plus 'Machine Spirit Documentation'",
    doneWhen: "Twice successfully invoked, time reclaimed, logic explained",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 8,
    title: "The Second Automation Rite",
    goal: "Forge your productivity servitor",
    deliverable: "One productivity automation plus tracking cogitator",
    doneWhen: "The servitor generates follow-ups autonomously with open items tracked",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 9,
    title: "The Context Engineering Protocol",
    goal: "Construct your Personal AI Operating Shrine",
    deliverable: "Structured context system and Professional Context Codex",
    doneWhen: "You possess one sanctum to reuse outputs and a Context Codex that elevates discourse",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
  {
    id: 10,
    title: "The Blessed Construction",
    goal: "Forge something with AI at its sacred core",
    deliverable: "Functioning application (chatbot, voice servitor, or tool) with AI essence",
    doneWhen: "You deploy a tool with AI at its heart that serves you or others",
    completed: false,
    notes: "",
    scorecard: { outcomeQuality: 0, timeSaved: 0, repeatability: 0 },
  },
];

// Mechanicus phrases for UI
export const mechanicusPhrases = {
  greeting: "The Omnissiah watches over your progress",
  complete: "The Machine Spirit is pleased",
  incomplete: "Awaiting sanctification",
  progress: "Path to Enlightenment",
  notes: "Cogitator Records",
  scorecard: "Sacred Metrics",
  outcome: "Quality of Output",
  timeSaved: "Efficiency Blessing",
  repeatability: "Reproducibility Index",
  allComplete: "PRAISE THE OMNISSIAH",
  startRite: "Initiate Protocol",
  viewRite: "Access Data-Shrine",
};
